import {
  Brand,
  EDMFormat,
  Topic,
  TopicCategory,
  Product,
  Template,
  TemplateCategoryGroup,
  CalendarItem,
  EmailBrief,
  CtaCopy,
} from '../types';

export const INITIAL_BRANDS: Brand[] = [
  { id: 'firemaple', name: 'FireMaple', color: '#ea580c', createdAt: '2026-01-01T00:00:00.000Z' },
  { id: 'sunseeker', name: 'Sunseeker', color: '#0284c7', createdAt: '2026-01-01T00:00:00.000Z' },
];

export const INITIAL_FORMATS: EDMFormat[] = [
  { id: 'fmt-1', name: '新品发布 (Product Launch)', order: 1 },
  { id: 'fmt-2', name: '促销特惠 (Promotion)', order: 2 },
  { id: 'fmt-3', name: '食谱教程 (Recipe)', order: 3 },
  { id: 'fmt-4', name: '干货指南 (Educational)', order: 4 },
  { id: 'fmt-5', name: '节日/季节 (Seasonal)', order: 5 },
  { id: 'fmt-6', name: '用户故事 (UGC)', order: 6 },
  { id: 'fmt-7', name: '品牌故事 (Storytelling)', order: 7 },
  { id: 'fmt-8', name: '其他 (Other)', order: 8 },
];

export const INITIAL_TOPIC_CATEGORIES: TopicCategory[] = [
  { id: 'cat-common', name: '普通', symbol: '✍️', color: '#64748b', isDefault: true },
  { id: 'cat-holiday', name: '节日活动', symbol: '🎉', color: '#ea580c', isDefault: true },
  { id: 'cat-promo', name: '促销特惠', symbol: '🔥', color: '#dc2626', isDefault: true },
  { id: 'cat-edu', name: '干货教程', symbol: '💡', color: '#0284c7', isDefault: true },
];

export const INITIAL_TOPICS: Topic[] = [
  {
    id: 'topic-1',
    brand: 'FireMaple',
    category: '普通',
    topic: '秋季露营烹饪与户外暖心餐',
    subtopic: '10分钟林间快煮拉面与热饮指南',
    emailType: 'Newsletter',
    marketingAngle: '秋日赏枫徒步的营地温暖美食灵感',
    notes: '主推 Petrel 极轻锅与 G2 蒸饭内胆，分享10分钟快手拉面食谱',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'topic-2',
    brand: 'FireMaple',
    category: '普通',
    topic: '超轻高山冲顶炉具专题',
    subtopic: '抗大风零下环境高效煮沸解决方案',
    emailType: '产品聚焦',
    marketingAngle: '不牺牲沸水速度的高山极轻装备减重',
    notes: '展示高海拔零下严寒测试对比',
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
  },
  {
    id: 'topic-3',
    brand: 'FireMaple',
    category: '节日活动',
    topic: '黑五 VIP 抢先购营地厨房专场',
    subtopic: '订阅用户专享低至7折+满赠好礼',
    emailType: '节日大促',
    marketingAngle: '年度底价早鸟开抢，全场爆款炉具套装直降',
    notes: '满$120赠送定制钛合金折叠叉勺',
    createdAt: '2026-09-03T10:00:00.000Z',
    updatedAt: '2026-09-03T10:00:00.000Z',
  },
  {
    id: 'topic-4',
    brand: 'Sunseeker',
    category: '普通',
    topic: '荒野越野车宿营地搭建指南',
    subtopic: '远离电网72小时脱困与营地照明方案',
    emailType: '干货教程',
    marketingAngle: '如何在峡谷荒野中高效完成车顶侧帐搭建',
    notes: '重点展示 Nomad 太阳能营地灯和侧帐',
    createdAt: '2026-09-04T10:00:00.000Z',
    updatedAt: '2026-09-04T10:00:00.000Z',
  },
  {
    id: 'topic-5',
    brand: 'Sunseeker',
    category: '节日活动',
    topic: '万圣节南瓜露营车队狂欢促',
    subtopic: '秋冬车宿保暖装备限时特惠',
    emailType: '节日促销',
    marketingAngle: '秋夜露营篝火装备限时85折',
    notes: '主推折叠营地桌椅与车载保温箱',
    createdAt: '2026-09-05T10:00:00.000Z',
    updatedAt: '2026-09-05T10:00:00.000Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-fm-01',
    brand: 'FireMaple',
    productName: 'Petrel 600ml Backpacking Pot',
    sku: 'FM-POT-PET600',
    discount: '限时85折优惠',
    originalPrice: '$49.99',
    price: '$39.95',
    productUrl: 'https://firemaple.com/products/petrel-ultralight-pot',
    specifications: '重量：145g (5.1 oz)\n尺寸：102 x 102 x 136 mm\n材质：硬质阳极氧化铝 / Tritan / 食品级硅胶',
    targetUseCases: '单人长途徒步、快速穿越、极简露营',
    descriptions: [
      {
        id: 'desc-1',
        keyword: '短描述',
        content: '超轻硬质阳极氧化铝户外锅，配聚能环底，煮水效率提升30%。',
      },
      {
        id: 'desc-2',
        keyword: '长描述',
        content: '专为单人徒步与高山快穿设计的超轻耐磨聚能锅，底部集成蜂窝聚能环与锁扣式隔热手柄，可完美收纳100g气罐与微型气炉。',
      },
      {
        id: 'desc-3',
        keyword: '海外官网风',
        content: 'Engineered for thru-hikers who count every gram. Features heat-exchange fins that cut boil times significantly while resisting harsh alpine wind.',
      },
    ],
    featuresList: [
      {
        id: 'feat-1',
        name: '底部高效聚能环系统',
        descriptions: [
          { id: 'fdesc-1', style: '技术参数风', text: '底部集成阳极氧化铝聚能环，热效率提升30%，煮沸500ml水仅需1分50秒。' },
          { id: 'fdesc-2', style: '场景体验风', text: '在山脊狂风中也能牢牢锁住炉火热量，省时又省气罐燃料。' },
          { id: 'fdesc-3', style: '口语短句风', text: '风再大水也飞速烧开，比普通锅快了将近一倍！' },
        ],
      },
      {
        id: 'feat-2',
        name: '折叠防烫锁扣手柄',
        descriptions: [
          { id: 'fdesc-4', style: '技术参数风', text: '双侧包覆食品级耐温硅胶套，折叠后锁紧牢固，不晃动。' },
          { id: 'fdesc-5', style: '痛点转化风', text: '彻底告别手抖打翻热汤的尴尬，倾倒热饮稳固安全。' },
        ],
      },
    ],
    productStatus: 'Active',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'prod-fm-02',
    brand: 'FireMaple',
    productName: 'G2 Rice Cooker Insert',
    sku: 'FM-ACC-G2RC',
    discount: '立减 $5',
    originalPrice: '$29.90',
    price: '$24.90',
    productUrl: 'https://firemaple.com/products/g2-rice-cooker-insert',
    specifications: '重量：98g\n容量：1-2人份 (200g 生米)\n材质：食品级铝合金配不沾陶瓷涂层',
    targetUseCases: '露营蒸饭、面点加热、户外轻食',
    descriptions: [
      {
        id: 'desc-g2-1',
        keyword: '短描述',
        content: '微孔导气聚能蒸米内胆，让户外锅秒变全自动防糊米饭蒸锅。',
      },
      {
        id: 'desc-g2-2',
        keyword: '长描述',
        content: '利用底部精密微孔蒸汽环流设计，均匀传导水蒸气，告别营地煮夹生饭或烧焦锅底的困扰，同时适合蒸饺子与温热食物。',
      },
    ],
    featuresList: [
      {
        id: 'feat-g2-1',
        name: '底部蒸汽微喷技术',
        descriptions: [
          { id: 'fdesc-g2-1', style: '技术参数风', text: '360°立体环绕蒸汽喷孔，确保米粒全方位受热均匀受水。' },
          { id: 'fdesc-g2-2', style: '场景体验风', text: '在荒野里也能吃上一口软糯不夹生、香气扑鼻的热米饭。' },
        ],
      },
    ],
    productStatus: 'Active',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'prod-ss-01',
    brand: 'Sunseeker',
    productName: 'Nomad Solar Lantern 300L',
    sku: 'SS-LGT-NOM300',
    discount: '新品特惠',
    originalPrice: '$45.00',
    price: '$34.99',
    productUrl: 'https://sunseekergear.com/products/nomad-solar-lantern',
    specifications: '亮度：30-300流明\n电池：4000mAh 锂电池\n防水：IP67 防水抗跌落',
    targetUseCases: '营地照明、车顶帐篷挂灯、离网应急充电',
    descriptions: [
      {
        id: 'desc-ss-1',
        keyword: '短描述',
        content: '折叠式太阳能防水营地灯，自带4000mAh应急移动电源。',
      },
      {
        id: 'desc-ss-2',
        keyword: '长描述',
        content: '兼具氛围烛光与300流明强光，顶部配单晶硅太阳能光伏板，可压缩折叠至2.5cm，户外随时挂在背包上光伏补电。',
      },
    ],
    featuresList: [
      {
        id: 'feat-ss-1',
        name: '单晶硅自发电面板',
        descriptions: [
          { id: 'fdesc-ss-1', style: '技术参数风', text: '转化率达21%的微型单晶硅光伏组件，日照即可自动涓流补电。' },
          { id: 'fdesc-ss-2', style: '场景体验风', text: '告别找插座焦虑，挂在背包上晒晒太阳，夜晚营地就有持续暖光。' },
        ],
      },
      {
        id: 'feat-ss-2',
        name: '双向应急充放电接口',
        descriptions: [
          { id: 'fdesc-ss-3', style: '痛点转化风', text: '手机电量告急？直接插上营地灯迅速应急回血。' },
        ],
      },
    ],
    productStatus: 'Active',
    createdAt: '2026-09-02T10:00:00.000Z',
    updatedAt: '2026-09-02T10:00:00.000Z',
  },
];

export const INITIAL_TEMPLATE_CATEGORY_GROUPS: TemplateCategoryGroup[] = [
  {
    id: 'group-hero',
    name: 'HERO',
    subcategories: ['大图视觉首焦', '左右图文首焦', '倒计时活动首焦', '动态GIF首焦'],
  },
  {
    id: 'group-product',
    name: 'PRODUCT',
    subcategories: ['单品聚焦', '双列产品网格', '三列瀑布流', '对比参数卡片'],
  },
  {
    id: 'group-content',
    name: 'CONTENT',
    subcategories: ['食谱与干货步骤', '用户评价UGC', '品牌故事与创始人', '福利与优惠券'],
  },
];

export const INITIAL_TEMPLATES: Template[] = [
  {
    id: 'tpl-1',
    templateName: 'Autumn Warmth Split Hero 01',
    mainCategory: 'HERO',
    subCategory: '大图视觉首焦',
    brand: 'All',
    screenshotUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80',
    referenceUrl: 'https://reallygoodemails.com/search/emails/outdoor%20autumn',
    description: '暖色调森林露营大图首焦，配半透明遮罩与主副标题，非常适合季节性营销活动主推。',
    tags: ['hero-banner', 'seasonal', 'warm-tones', 'lifestyle'],
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'tpl-2',
    templateName: 'Dual Product Feature Grid 02',
    mainCategory: 'PRODUCT',
    subCategory: '双列产品网格',
    brand: 'All',
    screenshotUrl: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=600&auto=format&fit=crop&q=80',
    referenceUrl: 'https://reallygoodemails.com/search/emails/product%20launch%20grid',
    description: '左右交替双列网格，白底产品特写搭配核心技术卖点提炼与独立CTA。',
    tags: ['product-grid', 'specs-card', 'side-by-side', '2-column'],
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'tpl-3',
    templateName: 'Backcountry Recipe Step-by-Step Card 01',
    mainCategory: 'CONTENT',
    subCategory: '食谱与干货步骤',
    brand: 'FireMaple',
    screenshotUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80',
    referenceUrl: 'https://reallygoodemails.com/search/emails/recipe%20steps',
    description: '户外三步快手法烹饪教学卡片，图文并茂展示装备使用步骤与食材配比。',
    tags: ['recipe', 'how-to', 'step-by-step', 'content'],
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'tpl-4',
    templateName: 'Black Friday VIP Early Access Banner 01',
    mainCategory: 'HERO',
    subCategory: '倒计时活动首焦',
    brand: 'All',
    screenshotUrl: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&auto=format&fit=crop&q=80',
    referenceUrl: 'https://reallygoodemails.com/search/emails/black%20friday',
    description: '黑金色调强视觉冲击促销首焦，居中大号折扣信息与VIP专享券码。',
    tags: ['black-friday', 'promotion', 'hero', 'discount'],
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
];

export const INITIAL_CTA_COPIES: CtaCopy[] = [
  // 通用型
  { id: 'cta-1', text: '立即探索', category: '通用型', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-2', text: '了解更多', category: '通用型', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-3', text: '查看详情', category: '通用型', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-4', text: '探索全系列', category: '通用型', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-5', text: '发现装备', category: '通用型', createdAt: '2026-09-01T00:00:00.000Z' },
  // 转化类
  { id: 'cta-6', text: '立即选购', category: '转化类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-7', text: '加入购物车', category: '转化类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-8', text: '抢先锁定', category: '转化类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-9', text: '立即开抢', category: '转化类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-10', text: '前往结账', category: '转化类', createdAt: '2026-09-01T00:00:00.000Z' },
  // 促销类
  { id: 'cta-11', text: '立即领券立减', category: '促销类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-12', text: '享VIP专属特惠', category: '促销类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-13', text: '解锁限时好礼', category: '促销类', createdAt: '2026-09-01T00:00:00.000Z' },
  { id: 'cta-14', text: '直达黑五专场', category: '促销类', createdAt: '2026-09-01T00:00:00.000Z' },
];

export const INITIAL_CALENDAR_ITEMS: CalendarItem[] = [
  {
    id: 'cal-fm-01',
    brand: 'FireMaple',
    date: '2026-10-15',
    topic: '秋季露营烹饪与户外暖心餐',
    topicId: 'topic-1',
    topicCategory: '普通',
    subtopic: '10分钟林间快煮拉面与热饮指南',
    emailType: 'Newsletter',
    marketingAngle: '秋日赏枫徒步的营地温暖美食灵感',
    productIds: ['prod-fm-01', 'prod-fm-02'],
    productNames: ['Petrel 600ml Backpacking Pot', 'G2 Rice Cooker Insert'],
    format: '食谱教程 (Recipe)',
    campaignGoal: '提升秋季配件及小烹饪组合的连带转化率',
    notes: '建议重点突出快沸拉面与蒸米饭的高效组合',
    status: 'Planned',
    hasBrief: true,
    briefId: 'brief-fm-01',
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'cal-ss-01',
    brand: 'Sunseeker',
    date: '2026-10-15',
    topic: '荒野越野车宿营地搭建指南',
    topicId: 'topic-4',
    topicCategory: '普通',
    subtopic: '远离电网72小时脱困与营地照明方案',
    emailType: '干货教程',
    marketingAngle: '如何在峡谷荒野中高效完成车顶侧帐搭建',
    productIds: ['prod-ss-01'],
    productNames: ['Nomad Solar Lantern 300L'],
    format: '干货指南 (Educational)',
    campaignGoal: '推广越野车宿照明与离网电源理念',
    notes: '与 Nomad 太阳能灯做强绑定介绍',
    status: 'Planned',
    hasBrief: false,
    createdAt: '2026-09-04T10:00:00.000Z',
    updatedAt: '2026-09-04T10:00:00.000Z',
  },
];

export const INITIAL_BRIEFS: EmailBrief[] = [
  {
    id: 'brief-fm-01',
    calendarItemId: 'cal-fm-01',
    brand: 'FireMaple',
    date: '2026-10-15',
    topic: '秋季露营烹饪与户外暖心餐',
    subtopic: '10分钟林间快煮拉面与热饮指南',
    subjectLine: '🍁 秋意正浓，奉上你的10分钟营地暖胃热食指南',
    preheader: 'Petrel 极轻聚能锅 + G2 内胆，山林快烹更省气',
    format: '食谱教程 (Recipe)',
    productIds: ['prod-fm-01', 'prod-fm-02'],
    positions: [
      {
        id: 'pos-1',
        name: 'Hero 首焦大图区',
        order: 1,
        templateId: 'tpl-1',
        templateName: 'Autumn Warmth Split Hero 01',
        templateScreenshot: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=600&auto=format&fit=crop&q=80',
        content: '【主题】秋季露营烹饪与户外暖心餐\n【副标】10分钟林间快煮拉面与热饮指南\n在红叶纷飞的山林露营，最惬意不过一碗热腾腾的快煮鲜味拉面。',
        productIds: ['prod-fm-01'],
        productNames: ['Petrel 600ml Backpacking Pot'],
        link: 'https://firemaple.com/products/petrel-ultralight-pot',
        keyRequirements: '图片风格温暖浓郁，展示晨雾或秋叶环境下的热气腾腾拉面场景，大标题突出秋日暖心。',
        ctas: [
          { id: 'cta-p1-1', text: '探索秋日美食指南', link: 'https://firemaple.com/products/petrel-ultralight-pot', category: '通用型' },
        ],
      },
      {
        id: 'pos-2',
        name: 'Section 1 核心单品推荐',
        order: 2,
        templateId: 'tpl-2',
        templateName: 'Dual Product Feature Grid 02',
        templateScreenshot: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?w=600&auto=format&fit=crop&q=80',
        content: 'Petrel 600ml 极轻聚能锅 —— 底部聚能环提升 30% 热效率，高山冷风中煮水飞速。',
        productIds: ['prod-fm-01', 'prod-fm-02'],
        productNames: ['Petrel 600ml Backpacking Pot', 'G2 Rice Cooker Insert'],
        link: 'https://firemaple.com/products/petrel-ultralight-pot',
        keyRequirements: '展示产品白色高光渲染图，突出聚能环截面与超轻手感对比。',
        ctas: [
          { id: 'cta-p2-1', text: '立省15% 抢先购', link: 'https://firemaple.com/products/petrel-ultralight-pot', category: '促销类' },
        ],
      },
    ],
    createdAt: '2026-09-01T10:00:00.000Z',
    updatedAt: '2026-09-01T10:00:00.000Z',
  },
];
